### ISSUE TITLE
Wyszukiwanie w słowniku Collins nie działa

### ISSUE THREAD

**Issue by PsychoThinker** [gryzus24/anki-dodawacz#14]
Operacje wyszukiwania kończą się komunikatem np.: Collins 'car' not found

**Comment by gryzus24** [comment]
Collins postanowił blokować dostęp klientom nie wysyłających specyficznych ciasteczek lub obsługujących javascriptu, jak na razie nie udało mi się wysłać poprawnego zapytania, nie wiem czy w ogóle z aktualnymi bibliotekami jest to możliwe.

**Comment by gryzus24** [comment]
Collins jakimś cudem zaczął działać ponownie. Wciąż używa starego ekstraktora bazującego na bs4, ale działa, więc zamykam na tę chwilę.
