### ISSUE TITLE
Czy można wybrać pozycję spoza zakresu 1-20 wyniku?

### ISSUE THREAD

**Issue by PsychoThinker** [gryzus24/anki-dodawacz#16]
Wcześnie można było ograniczyć liczbę pozycji w wyniku wybierając np. rzeczownik, ale w nowej wersji aplikacji chyba nie ma takiej możliwości :(. Nie łatwiej było by pozwolić przescrollować się po wszystkicg pozycjach i np. spacją wybrać te które nas interesują ?

**Comment by gryzus24** [comment]
Tak, to jest dobry pomysł. Myślę, że najlepsza implementacja to byłby po prostu kursor którym możemy nawigować z definicji na definicję (`j`, `k`, strzałki) i zaznaczyć aktualnie wybrane pole spacją lub enterem. Problemem tutaj jest jak odwzorować kursor a jak zaznaczenie, co jest dosyć subiektywne, więc należy dodać tutaj jakiś sposób na konfigurację.

Osobiście wolę zaznaczanie numerkami i wciśnięcie `c` lub `C`, bo zwykle zaznaczam od 1 do 3 definicji, więc wychodzi mniej kliknięć niż gdyby to robić za pomocą kursora, ale nic nie stoi na przeszkodzie, aby te dwie funkcje koegzystowały.

Obecnie, aby zaznaczyć dowolne definicje należy użyć myszki. Raczej rzadko zdarza się taka potrzeba w AHD, ale w innych słownikach może być różnie. W każdym razie, funkcja kursora jest pożądana.
